### PR TITLE
feat/hero section updated

### PR DESCRIPTION
**Pull request by avinashkranjan**

### CODE REVIEW

**Review by mdsams — CHANGES_REQUESTED** [review]
1)Keep the speed of the particles stable all the time. The speed is increasing rapidly. Due to that, it is looking a little messy.
2) The particles are getting stuck for some second. Once see to that issue.
Apart from that, it looks awesome

**Comment by cosmo3769** [comment]
@avinashkranjan The header looks nice. Some points to look over: 

* The clock is overlapping with about section when reducing the width and height of the page.(inspect)
* We can remove the tsparticles as it don't look much professional.(Let's discuss on this matter) @mdsams @madihamallick @shalini-tiwari

**Comment by avinashkranjan** [comment]
> @avinashkranjan The header looks nice. Some points to look over:
> 
> * The clock is overlapping with about section when reducing the width and height of the page.(inspect)
> * We can remove the tsparticles as it don't look much professional.(Let's discuss on this matter) @mdsams @madihamallick @shalini-tiwari

Will Remove `tsparticles` then and resolve the overlapping issue.

**Comment by mdsams** [comment]
The tsparticles are looking good just have to give some fine touch to it. I had a talk with the other team and they find it unique and appreciated that. We will have a talk on this @cosmo3769 @avinashkranjan

**Comment by avinashkranjan** [comment]
> The tsparticles are looking good just have to give some fine touch to it. I had a talk with the other team and they find it unique and appreciated that. We will have a talk on this @cosmo3769 @avinashkranjan

Will add it again 😅

**Comment by cosmo3769** [comment]
@xprilion What do you think about it? Should we keep the tsparticles or not?

**Review by cosmo3769 — APPROVED** [review]

**Pull request merged**
