### PR TITLE
Footer and FAQ

### PR DESCRIPTION
**Pull request by madihamallick**

### CODE REVIEW

**Comment by cosmo3769** [comment]
@madihamallick The footer and faq both looks good. One thing to look over: 

* The faq section is opening on click, but not closing. 

One suggestion: 

* Can we place the social media links in footer section under first column(below GDG Cloud kolkata logo and title).

**Comment by madihamallick** [comment]
> 

Sure, will make the changes soon.

**Comment by madihamallick** [comment]
> @madihamallick The footer and faq both looks good. One thing to look over:
> 
> * The faq section is opening on click, but not closing.
> 
> One suggestion:
> 
> * Can we place the social media links in footer section under first column(below GDG Cloud kolkata logo and title).
Sure, will make the changes soon.

**Review by avinashkranjan — CHANGES_REQUESTED** [review]
LGTM... Rest Make the changes as @cosmo3769 Mentioned.

**Review by cosmo3769 — APPROVED** [review]
LGTM

**Review by avinashkranjan — APPROVED** [review]
LGTM. Resolve the Conflicts @madihamallick We'll merge the PR.

**Comment by madihamallick** [comment]
> LGTM. Resolve the Conflicts @madihamallick We'll merge the PR.

Donee

**Pull request merged**
